### ISSUE TITLE
Epic - ATD AMANDA Backlog

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#141] opened 2019-09-05 18:57 UTC
## Description
The purpose of this project is to contract with an AMANDA developer to deliver all items on ATD's AMANDA backlog.

**Comment by amenity** [comment] 2020-02-25 23:44
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/432

**Closed as completed by amenity** 2020-02-25 23:44 UTC
Labels: Duplicate, Epic, Product: AMANDA
